[package]
name = "fmtui"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.28.1"
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
